### ISSUE TITLE
Feature suggestion: configure feature set

### ISSUE THREAD

**Issue by ddugovic** [Glitched519/Processor#12]
I like inviting open source bots to my server, however I don't necessarily want all of these features enabled.  I already have a moderation bot, a math bot, etc.

![image](https://user-images.githubusercontent.com/1834123/119137528-80e51900-ba06-11eb-9f44-e0b764a5dd92.png)

**Comment by NoobCoderJJ** [comment]
Maybe trying to remove the codes you don't want,
 Can help!
