### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AnaheimDucks16** [Glitched519/Processor#13]
My feature request is to make a soft ban command for moderation. A soft ban command bans the user then unbans them.

**Comment by ultrasarker** [comment]
For softban, I believe you mean by specifying a duration (e.g. **4h** [4 hours], **6d** [6 days], etc.) for the ban?

**Comment by AnaheimDucks16** [comment]
Kind of, the softban is just a command that bans and unbans instantly. And deletes a certain amount of messages. Ex. Last 24 hours of messages deleted at once

**Comment by oodvg** [comment]
> For softban, I believe you mean by specifying a duration (e.g. **4h** [4 hours], **6d** [6 days], etc.) for the ban?

all softban does is bans the user just to delete the users messages over the last 7 days. I believe you are talking about tempban.
