### ISSUE TITLE
How do i self host the bot?

### ISSUE THREAD

**Issue by hotsu0p** [Glitched519/Processor#22]
How do i self host the bot

**Comment by ultrasarker** [comment]
There are two ways I suggest running the bot:

## Via Node
1. Make sure you are in `Processor/` folder.
2. Run `npm i`
3. Change directory into `src/` folder.
4. Run `node processor.js`

## Via `pm2` (Make sure it is installed properly)
1. Make sure you are in `Processor/` folder.
2. Run `pm2 start`

[PM2 Documentation](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/)

**Comment by hotsu0p** [comment]
I get this

node:internal/modules/cjs/loader:1327
    throw err;
    ^

SyntaxError: C:\Users\Processor\src\config.json: Unexpected token : in JSON at position 11
    at parse (<anonymous>)
